// Translate only at the admin API boundary; shared controllers also serve the public API.
const messages: Record<string, string> = {
  "Name is required": "名称不能为空",
  "Valid API key id is required": "请提供有效的 API 密钥 ID",
  "Error sending email via SMTP": "通过 SMTP 发送邮件失败",
  "Title and startDateTime are required": "标题和开始时间不能为空",
  "End date time cannot be less than start date time": "结束时间不能早于开始时间",
  "Monitor impact must be either DOWN, DEGRADED, MAINTENANCE": "监控影响类型必须为 DOWN、DEGRADED 或 MAINTENANCE",
  "Title is required": "标题不能为空",
  "Start date/time is required": "开始日期和时间不能为空",
  "RRULE is required": "重复规则 RRULE 不能为空",
  "Duration must be greater than 0": "持续时间必须大于 0",
  "End date/time must be after start date/time": "结束时间必须晚于开始时间",
  "At least one monitor is required": "请至少选择一个监控项",
  "Failed to retrieve created monitor alert config": "获取新建的监控告警配置失败",
  "id is required for update": "更新时必须提供 ID",
  "Failed to retrieve updated monitor alert config": "获取更新后的监控告警配置失败",
  "Failed to retrieve created monitor alert": "获取新建的监控告警失败",
  "Failed to retrieve updated monitor alert": "获取更新后的监控告警失败",
  "Monitor tag is required": "监控项标识不能为空",
  "Monitor tag must be URL-friendly: only lowercase letters, numbers, hyphens, and underscores. Must start and end with a letter or number.":
    "监控项标识只能包含小写字母、数字、连字符和下划线，且必须以字母或数字开头和结尾。",
  "Invalid data": "数据无效",
  "Proxy URL must be a valid http:// or https:// URL": "代理 URL 必须是有效的 http:// 或 https:// 地址",
  "monitor id must be empty or 0": "新建监控项的 ID 必须为空或 0",
  "Source monitor tag is required": "源监控项标识不能为空",
  "Tag is required": "标识不能为空",
  "New tag must be different from source tag": "新标识不能与源监控项标识相同",
  "Source monitor not found": "未找到源监控项",
  "Monitor tag already exists": "监控项标识已存在",
  "Monitor name already exists": "监控项名称已存在",
  "monitor id cannot be empty or 0": "监控项 ID 不能为空或 0",
  "Monitor not found": "未找到监控项",
  "Monitor type data not found": "未找到监控类型配置",
  "Invalid heartbeat secret": "心跳密钥无效",
  "No claims in token response": "令牌响应中没有声明",
  "No subject (sub) claim in token": "令牌中没有主体声明（sub）",
  "No email in ID token and no access_token available for userinfo lookup":
    "ID 令牌中没有邮箱，且没有可用于查询用户信息的 access_token",
  "No email claim found in token or userinfo response": "令牌或用户信息响应中没有邮箱声明",
  "Failed to create OIDC user": "创建 OIDC 用户失败",
  "User disappeared during role sync": "角色同步时用户已不存在",
  "page_path, page_title, and page_header are required": "页面路径、标题和页眉不能为空",
  "Cannot delete the home page": "不能删除首页",
  "Email cannot be empty": "邮箱不能为空",
  "Please enter a valid email address": "请输入有效的邮箱地址",
  "Name cannot be empty": "名称不能为空",
  "Name must be at least 2 characters": "名称至少需要 2 个字符",
  "Name must be less than 100 characters": "名称必须少于 100 个字符",
  "Password cannot be updated using this method": "不能通过此方式修改密码",
  "Role cannot be updated using this method": "不能通过此方式修改角色",
  "Update value cannot be empty": "更新值不能为空",
  "Invalid update key": "更新字段无效",
  "At least one role is required": "请至少选择一个角色",
  "Password cannot be empty": "密码不能为空",
  "Passwords do not match": "两次输入的密码不一致",
  "Password must contain at least 8 characters, one uppercase letter, one lowercase letter and one number":
    "密码至少需要 8 个字符，包含大写字母、小写字母和数字",
  "Password must contain at least one digit, one lowercase letter, one uppercase letter, and have a minimum length of 8 characters":
    "密码至少需要 8 个字符，包含大写字母、小写字母和数字",
  "User not found": "未找到用户",
  "Owner must retain the admin role": "所有者必须保留管理员角色",
  "is_active is required": "启用状态（is_active）不能为空",
  "Owner account cannot be deactivated": "不能停用所有者账户",
  "Password is required": "密码不能为空",
  "User has already set their password": "用户已设置密码",
  "User ID is required": "用户 ID 不能为空",
  "User email is already verified": "用户邮箱已验证",
  "Verify email template not found": "未找到邮箱验证模板",
  "Role ID is required": "角色 ID 不能为空",
  "Role ID can only contain lowercase letters, numbers, underscores, and hyphens":
    "角色 ID 只能包含小写字母、数字、下划线和连字符",
  "Role name is required": "角色名称不能为空",
  "Failed to create role": "创建角色失败",
  "Readonly roles cannot be updated": "不能修改只读角色",
  "Role name cannot be empty": "角色名称不能为空",
  "Status must be ACTIVE or INACTIVE": "状态必须为 ACTIVE 或 INACTIVE",
  "No valid fields to update": "没有可更新的有效字段",
  "Failed to retrieve updated role": "获取更新后的角色失败",
  "Readonly roles cannot be deleted": "不能删除只读角色",
  "Target role ID is required for migration": "迁移时必须提供目标角色 ID",
  "Target role cannot be the same as the role being deleted": "目标角色不能与待删除的角色相同",
  "Cannot migrate users to an inactive role": "不能将用户迁移到停用的角色",
  "Readonly roles cannot have their permissions modified": "不能修改只读角色的权限",
  "User is already assigned to this role": "用户已拥有此角色",
  "The owner cannot be removed from the admin role": "不能移除所有者的管理员角色",
  "You do not have permission to perform this action": "你没有执行此操作的权限",
  "Method not found": "未找到订阅方式",
  "Subscriber not found": "未找到订阅者",
  "Invalid email address": "邮箱地址无效",
  "Invalid or expired token": "令牌无效或已过期",
  "User not found or inactive": "用户不存在或已停用",
  "Subscription method not found or inactive": "订阅方式不存在或已停用",
  "Email template not found": "未找到邮件模板",
  "Failed to send verification email": "发送验证邮件失败",
  "Invalid verification code": "验证码无效",
  "Verification code expired": "验证码已过期",
  "Invalid token": "令牌无效",
  "Docker host address is empty": "Docker 主机地址不能为空",
  "Docker socket path is empty": "Docker 套接字路径不能为空",
  "Provide the TLS client certificate and key together": "请同时提供 TLS 客户端证书和私钥",
  "Docker socket not found. Is the daemon running and the socket mounted into Kener?":
    "未找到 Docker 套接字，请确认守护进程已运行且套接字已挂载到 Kener。",
  "Permission denied on the Docker socket. The Kener process needs access to it.":
    "没有访问 Docker 套接字的权限，请授予 Kener 进程访问权限。",
  "Connection refused by the Docker daemon": "Docker 守护进程拒绝连接",
  "Unknown Docker API error": "未知的 Docker API 错误",
  "Email not configured properly. Please check SMTP or Resend configuration.":
    "邮件配置不正确，请检查 SMTP 或 Resend 配置。",
  "No valid email configuration found. Please check your SMTP or Resend settings.":
    "未找到有效的邮件配置，请检查 SMTP 或 Resend 设置。",
};

// Match complete application messages, leaving embedded values and external diagnostics intact.
const patterns: [RegExp, string][] = [
  [/^Template with ID (.*) not found$/, "未找到模板，ID：$1"],
  [/^Incident with id (.*) (?:does not exist|not found)$/, "未找到故障事件，ID：$1"],
  [/^Monitor with tag (.*) (?:does not exist|not found)$/, "未找到监控项，标识：$1"],
  [/^Comment with id (.*) does not exist$/, "未找到评论，ID：$1"],
  [/^Maintenance with id (.*) does not exist$/, "未找到维护计划，ID：$1"],
  [/^Maintenance event with id (.*) does not exist$/, "未找到维护事件，ID：$1"],
  [/^Invalid status: (.*)\. Allowed values are (.*) and (.*)$/, "状态无效：$1。允许的值：$2、$3"],
  [/^Cannot transition event from (.*) to (.*)$/, "不能将事件状态从 $1 更改为 $2"],
  [/^Monitor (.*) is not attached to maintenance (.*)$/, "监控项 $1 未关联到维护计划 $2"],
  [/^Invalid alert_for value: (.*)\. Must be one of: (.*)$/, "告警类型（alert_for）无效：$1。允许的值：$2"],
  [/^Invalid severity value: (.*)\. Must be one of: (.*)$/, "严重程度（severity）无效：$1。允许的值：$2"],
  [/^Invalid value: (.*)\. Must be one of: (.*)$/, "值无效：$1。允许的值：$2"],
  [
    /^Invalid alert_value for STATUS alert: (.*)\. Must be one of: (.*)$/,
    "状态告警的值（alert_value）无效：$1。允许的值：$2",
  ],
  [
    /^Invalid alert_value for LATENCY alert: (.*)\. Must be a positive number \(milliseconds\)$/,
    "延迟告警的值（alert_value）无效：$1。必须是正数，单位为毫秒",
  ],
  [
    /^Invalid alert_value for UPTIME alert: (.*)\. Must be a number between 0 and 100 \(percentage\)$/,
    "可用率告警的值（alert_value）无效：$1。必须是 0 到 100 之间的百分比数值",
  ],
  [
    /^Invalid (failure_threshold|success_threshold): (.*)\. Must be a positive integer >= 1$/,
    "阈值 $1 无效：$2。必须是大于或等于 1 的正整数",
  ],
  [/^Monitor alert config with id (.*) not found$/, "未找到监控告警配置，ID：$1"],
  [/^Trigger with id (.*) not found$/, "未找到触发器，ID：$1"],
  [/^Invalid alert_status value: (.*)\. Must be one of: (.*)$/, "告警状态（alert_status）无效：$1。允许的值：$2"],
  [/^Monitor alert with id (.*) not found$/, "未找到监控告警，ID：$1"],
  [/^OIDC Discovery failed: ([\s\S]*)$/, "OIDC 自动发现失败：$1"],
  [/^Page with path "(.*)" already exists$/, "页面路径“$1”已存在"],
  [/^Page with id (.*) not found$/, "未找到页面，ID：$1"],
  [/^Monitor "(.*)" already exists on this page$/, "监控项“$1”已在此页面中"],
  [/^Monitor "(.*)" not found on this page$/, "此页面中未找到监控项“$1”"],
  [/^Invalid key: (.*)$/, "配置键无效：$1"],
  [/^Invalid value for key: (.*)$/, "配置值无效，配置键：$1"],
  [/^Invalid email: (.*)$/, "邮箱地址无效：$1"],
  [/^Role "(.*)" (?:does not exist|not found)$/, "未找到角色“$1”"],
  [/^Role "(.*)" is not active$/, "角色“$1”未启用"],
  [/^Unsupported update type: (.*)$/, "不支持的更新类型：$1"],
  [/^A user with email (.*) already exists$/, "邮箱 $1 对应的用户已存在"],
  [/^Role ID "(.*)" is restricted and cannot be used$/, "角色 ID“$1”为保留标识，不能使用"],
  [/^Role with ID "(.*)" already exists$/, "角色 ID“$1”已存在"],
  [/^Target role "(.*)" not found$/, "未找到目标角色“$1”"],
  [/^Docker connection type must be one of: (.*)$/, "Docker 连接类型必须为以下值之一：$1"],
  [/^Docker API request timed out after (\d+)ms$/, "Docker API 请求超时，已等待 $1 毫秒"],
  [/^Resend API error: ([\s\S]*)$/, "Resend API 错误：$1"],
  [/^Discord webhook request failed with status (\d+)$/, "Discord Webhook 请求失败，状态码：$1"],
  [/^Slack webhook request failed with status (\d+)$/, "Slack Webhook 请求失败，状态码：$1"],
  [/^Webhook request failed with status (\d+)$/, "Webhook 请求失败，状态码：$1"],
  [/^Error sending Discord notification: ([\s\S]*)$/, "发送 Discord 通知失败：$1"],
  [/^Error sending Slack notification: ([\s\S]*)$/, "发送 Slack 通知失败：$1"],
  [/^Error sending webhook: ([\s\S]*)$/, "发送 Webhook 失败：$1"],
];

export function localizeAdminError(message: string): string {
  if (Object.hasOwn(messages, message)) return messages[message];
  for (const [pattern, replacement] of patterns) {
    if (pattern.test(message)) return message.replace(pattern, replacement);
  }
  return message;
}
