import { EditorState } from "@codemirror/state";

export const adminEditorExtensions = [
  EditorState.phrases.of({
    Find: "查找",
    Replace: "替换",
    next: "下一个",
    previous: "上一个",
    all: "全部",
    "match case": "区分大小写",
    regexp: "正则表达式",
    "by word": "全字匹配",
    replace: "替换",
    "replace all": "全部替换",
    close: "关闭",
    "Go to line": "跳转到行",
    go: "跳转",
    "current match": "当前匹配项",
    "on line": "所在行",
    "replaced match on line $": "已替换第 $ 行的匹配项",
    "replaced $ matches": "已替换 $ 个匹配项",
    "Folded lines": "已折叠行",
    "Unfolded lines": "已展开行",
    to: "至",
    "folded code": "已折叠的代码",
    unfold: "展开",
    "Fold line": "折叠行",
    "Unfold line": "展开行",
    Completions: "补全建议",
    Diagnostics: "诊断",
    "No diagnostics": "没有诊断信息",
    "Selection deleted": "已删除所选内容",
    "Control character": "控制字符",
  }),
];
